### PR TITLE
build: update versions of node and npm for Volta

### PR DESCRIPTION
**Pull request by MrChocolatine**
## Problem

Something has been bothering me for a while: the different versions of Node.js in our `package.json`:

https://github.com/DazzlingFugu/ember-fr-guides-source/blob/2fe8c40e6828e9769120786031ad8c9ba7c6971b/package.json#L119-L121

https://github.com/DazzlingFugu/ember-fr-guides-source/blob/2fe8c40e6828e9769120786031ad8c9ba7c6971b/package.json#L125-L128

Which obviously, at first sight, is weird.

---

Even weirder, our `package-lock.json` uses the field `"lockfileVersion": 3` and the documentation says the value of `3` is used by npm v9:
  - https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#lockfileversion

    npm doc lockfileVersion

### Why this version of Node.js?

Use of the latest version of the v16 branch because:

1. First, #168 configured the first steps to use Node.js version >= 16 by upgrading `ember-cli` to version 3.28.6 (see also: https://github.com/ember-cli/ember-cli/blob/v5.6.0/docs/node-support.md#supported-version-matrix).

1. Then #174 restricted the use of Node.js version >= 16 only and configured our CI to do so.

Resources:
- https://nodejs.org/download/release/latest-v16.x/
- https://nodejs.org/dist/index.json

### Why this version of npm?

Use of the latest version of the v9 branch because:

- The latest version currently available, npm v10, is not compatible with Node.js v16:
  npm v10 not compatible with node v16

And the upstream repo also uses npm v9: https://github.com/ember-learn/guides-source/blob/fc0036b703e84b9cf3ab5c36e5ba947f9fa6e7b2/package.json#L120-L123

Resources:
- https://www.npmjs.com/package/npm?activeTab=versions

### Why the changes in the `package-lock.json`?

_(before the commit that regenerates the lockfile)_

These were generated after running the command `npm i`.

### Optional: regenerating the `package-lock.json` file

I am tempted to regenerate the `package-lock.json` file but let me know what you think.

I tried, everything went fine on the CI: https://github.com/DazzlingFugu/ember-fr-guides-source/actions/runs/7907843255?pr=240

## Note

Overall we will need to get rid of Node.js version 16 as soon as possible as it reached its end of life 
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
- https://github.com/nodejs/Release/#end-of-life-releases
- https://nodejs.org/en/blog/announcements/nodejs16-eol/

### CODE REVIEW

**Comment by BlueCutOfficial** [comment]
When I fetch the branch I have an error on build 🤔 I deleted my `node_modules` just in case but still the same result. 

<details>
  <summary>Log file</summary>

```
=================================================================================

ENV Summary:

  TIME: Thu Feb 15 2024 09:36:53 GMT+0100 (Central European Standard Time)
  TITLE: ember
  ARGV:
  - /Users/marine/Library/pnpm/nodejs/16.20.2/bin/node
  - /Users/marine/.nvm/versions/node/v16.17.1/bin/ember
  - s
  EXEC_PATH: /Users/marine/Library/pnpm/nodejs/16.20.2/bin/node
  TMPDIR: /var/folders/nb/_m8gp0_52s17rj4780nm3_600000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/marine/Library/pnpm
  - /opt/homebrew/opt/python@3.10/libexec/bin
  - /Users/marine/.nvm/versions/node/v16.17.1/bin
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Users/marine/Library/pnpm
  - /opt/homebrew/opt/python@3.10/libexec/bin
  - /Users/marine/.nvm/versions/node/v16.17.1/bin
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  PLATFORM: darwin arm64
  FREEMEM: 96829440
  TOTALMEM: 34359738368
  UPTIME: 8882511
  LOADAVG: 15.71630859375,10.12841796875,5.75537109375
  CPUS:
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.19.1
  - brotli: 1.0.9
  - cldr: 41.0
  - icu: 71.1
  - llhttp: 6.0.11
  - modules: 93
  - napi: 8
  - nghttp2: 1.47.0
  - nghttp3: 0.7.0
  - ngtcp2: 0.8.1
  - node: 16.20.2
  - openssl: 1.1.1v+quic
  - tz: 2022f
  - unicode: 14.0
  - uv: 1.43.0
  - v8: 9.4.146.26-node.26
  - zlib: 1.2.11
  - 

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: The comparison function must be either a function or undefined
    at Array.sort (<anonymous>)
    at stringify (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/json-stable-stringify/index.js:73:31)
    at stableStringify (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/json-stable-stringify/index.js:90:3)
    at FastBootConfig.toJSONString (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:170:12)
    at FastBootConfig.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:56:53)
    at TransformNodeWrapper.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli/dist/wrappers/transform-node.js:71:39)
    at /Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli/dist/builder.js:185:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Builder.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli/dist/builder.js:204:13)
    at async Builder.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/models/builder.js:197:11)
  - code: [undefined]
  - codeFrame: The comparison function must be either a function or undefined
  - errorMessage: The comparison function must be either a function or undefined
        at FastBootConfig (Generate: FastBoot package.json)
-~- created here: -~-
    at new Plugin (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli-plugin/index.js:7:31)
    at new FastBootConfig (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:18:5)
    at Class._buildFastbootConfigTree (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/index.js:301:12)
    at Class.treeForPublic (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/index.js:234:35)
    at Class._treeFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/broccoli/ember-app.js:721:26
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/broccoli/ember-app.js:719:32)
    at EmberApp.addonTreesFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/broccoli/ember-app.js:743:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: The comparison function must be either a function or undefined
        at FastBootConfig (Generate: FastBoot package.json)
-~- created here: -~-
    at new Plugin (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli-plugin/index.js:7:31)
    at new FastBootConfig (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:18:5)
    at Class._buildFastbootConfigTree (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/index.js:301:12)
    at Class.treeForPublic (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/index.js:234:35)
    at Class._treeFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/broccoli/ember-app.js:721:26
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/broccoli/ember-app.js:719:32)
    at EmberApp.addonTreesFor (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/broccoli/ember-app.js:743:17)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: Generate: FastBoot package.json
  - nodeName: FastBootConfig
  - originalErrorMessage: The comparison function must be either a function or undefined
  - stack: TypeError: The comparison function must be either a function or undefined
    at Array.sort (<anonymous>)
    at stringify (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/json-stable-stringify/index.js:73:31)
    at stableStringify (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/json-stable-stringify/index.js:90:3)
    at FastBootConfig.toJSONString (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:170:12)
    at FastBootConfig.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:56:53)
    at TransformNodeWrapper.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli/dist/wrappers/transform-node.js:71:39)
    at /Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli/dist/builder.js:185:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Builder.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/broccoli/dist/builder.js:204:13)
    at async Builder.build (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-fr-guides-source/node_modules/ember-cli/lib/models/builder.js:197:11)

=================================================================================
```

</details>

**Comment by MrChocolatine** [comment]
@BlueCutOfficial 

> When I fetch the branch I have an error on build 🤔 I deleted my `node_modules` just in case but still the same result.

Noted.
Also, in my PR I also find strange the changes in the lockfile (without the commit that regenerates it).

I will investigate more.

**Comment by MrChocolatine** [comment]
@BlueCutOfficial , can you just try without the last commit that regenerate the lockfile please?
Check out the branch and `git rebase --onto @^ @`.

**Comment by BlueCutOfficial** [comment]
Without the 2nd commit it works fine 👍 I could install the dependencies and run the app.

**Comment by MrChocolatine** [comment]
> Without the 2nd commit it works fine 👍 I could install the dependencies and run the app.

PR finalised then.

**Review by BlueCutOfficial — APPROVED** [review]

**Pull request merged**
